/*
  author: @ryvexc
  github: https://www.github.com/ryvexc/

  This file is generated by @ryvexc from github.com
  DO NOT EDIT THIS FILE.
*/

#include <iostream>

int main(int argc, char **argv)
{
  int exit_code = system(argv[1]);
  std::cout << std::endl
            << "Process ended with exit code " << exit_code << ".";
  std::cin.get();
}