/*
  author: @ryvexc
  github: https://www.github.com/ryvexc/

  This file is generated by @ryvexc from github.com
  for example C++ Main file.
*/

#include <iostream>
#include "include/hello_world.hpp"

using namespace std;

int main(int argc, char **argv)
{
  cout << "Hello, Ryve!" << endl;

  hello_world(); // this function is from "include/hello_world.hpp"
  return 0;
}
