/*
  author: @ryvexc
  github: https://www.github.com/ryvexc/

  This file is generated by @ryvexc from github.com
  for example C++ Header file.
*/

#include <iostream>
#include "hello_world.cpp"

void hello_world();