/*
  author: @ryvexc
  github: https://www.github.com/ryvexc/

  This file is generated by @ryvexc from github.com
  for example C++ Include file.
*/

#include <iostream>

using namespace std;

void hello_world()
{
  cout << "Hello World" << endl;
}